### ISSUE TITLE
Zero size output

### ISSUE THREAD

**Issue by gabest11** [nicoboss/nsZip#5]
https://github.com/nicoboss/nsZip/blob/ec19d046f2f2d9feb2b7cbb7906a81c2c5492b1b/LibHac/IO/StorageExtensions.cs#L71

No idea how this is supposed to work. GetSize returns 0 on output, remaining starts from 0.

**Comment by gabest11** [comment]
Oh, it is used at many different places. It happens when the final output is written in FolderToNSP. The output file is not preallocated.

**Comment by gabest11** [comment]
Fixing remaining does not seem to be enough. StorageBase.Write won't write a bit, because CanAutoExpand is false for FilePositionStorage and ValidateParameters rejects the offset (> length).

**Comment by nicoboss** [comment]
Could you please provide some more information how to reproduce that issue? I'm not really sure what you are try to fix. The CopyTo() implementation inside StorageExtensions.cs seems to be working properly given GetSize() was implemented properly in your IStorage implementation.
FolderToNSP and FolderToXCI still uses IFileSystem as input and IFile as output as implementing it with storages is quite complex as all file’s sizes contained in the NDV0/HDV0 container must be stored in its header.  Because of this currently all file sizes need to be known before building an NSP/XCI file requiring a temporary HDD write as the compressed file sizes can't be known until everything is fully compressed. A lot of efforts will be made to eliminate that by writing the header after adding all the files in the future. I know temporary HDD writes are very bad and eliminating them has quite high priority.
IStorage always needs to properly implement GetSize() for it to work properly. If implementing GetSize() isn't possible for technical reasons I recommend using a stream with CopyStream() instead.

**Comment by gabest11** [comment]
It's all good now. You have to test the code before my fix. If you want to repro now, change back the second argument in FolderTools.FolderToNSP.

`FilePositionStorage(outFile, true) => FilePositionStorage(outFile, false)`

StorageBase.ValidateParameters will throw the exception when it starts writing the final nspz.

**Comment by gabest11** [comment]
Initially, GetSize() returns 0 for nspz, that's where it needs to be excluded from that Math.Min.

**Comment by nicoboss** [comment]
I see I Implemented FilePositionStorage with automated file expansion but forgot activating CanAutoExpand in the base class causing ValidateParameters to throw an ArgumentException. FilePositionStorage is very new and not well-tested so great you found and fixed that bug. I can't think of any case where CanAutoExpand shouldn't be enabled so no need for a separate constructor - just enable it in the default one.
