### ISSUE TITLE
FileSystemExtensions.EnsureDirectoryExists does not work correctly

### ISSUE THREAD

**Issue by gabest11** [nicoboss/nsZip#7]
Noticed it when doing an Extract RomFS from the GUI.  It's the second part. Rewrite it like this:

https://github.com/nicoboss/nsZip/blob/bcf2e1477014a90a33bb1a7123bdcf2e245d75b0/LibHac/IO/FileSystemExtensions.cs#L236

`            for (; i <= path.Length; i++)`
`            {`
`                if (i > 1 && i == path.Length || path[i] == '/')`

edit: testing order is important

**Comment by nicoboss** [comment]
Thanks for reporting. You're right. I updated LibHac the last time on 26th July 2019 while this issue was fixed inside LibHac on 9th August 2019: https://github.com/Thealexbarney/LibHac/commit/ea2572c479072211985cc35acbba1d70b844905e
I will update the LibHac library used by nsZip later today in order to fix this issue.
